#!/bin/bash -l
#SBATCH --account=pi-lgagliardi
#SBATCH --qos=lgagliardi
#SBATCH --time=240:00:00
#SBATCH --nodes=1
#SBATCH --partition=lgagliardi-hm,lgagliardi-amd,caslake
#SBATCH --ntasks-per-node=32
#SBATCH --mem-per-cpu=8G
#SBATCH --job-name=Fe3_1516_15
#SBATCH --error=error.%j.err

export PYTHONPATH=/project/lgagliardi/shared/Apps/pyscf:$PYTHONPATH
export PYTHONPATH=/project/lgagliardi/valayagarawal/Apps/mrh-cpu:$PYTHONPATH 
#export PYTHONPATH=/project/lgagliardi/shared/Apps:$PYTHONPATH 

module load python
module load intel
module load gcc

ulimit -s unlimited
export PYSCF_MAX_MEMORY=256000
/usr/bin/time --verbose python $1 

